### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by oleteacher** [nliautaud/pico-content-editor#10]
Great plugin, thank you for sharing.

I have installed the editor and all seems good except uploading images. they get uploaded to the images folder, but cannot insert them into content.

Have tried on Pico V1 and the 2 beta with same results. Running PHP 7.2.1

Here is the logs from console and any suggestions to solve much appreciated:

```
File(13539) {name: "avatar04.png", lastModified: 1499535957000, lastModifiedDate: Sat Jul 08 2017 12:45:57 GMT-0500 (Central Daylight Time), webkitRelativePath: "", size: 13539, …}lastModified: 1499535957000lastModifiedDate: Sat Jul 08 2017 12:45:57 GMT-0500 (Central Daylight Time) {}name: "avatar04.png"size: 13539type: "image/png"webkitRelativePath: ""__proto__: File


Uncaught TypeError: Cannot read property 'path' of undefined
    at XMLHttpRequest.xhrComplete (editor.js:73)
	
	
xhrComplete @ editor.js:73
XMLHttpRequest.send (async)
(anonymous) @ editor.js:104
a.dispatchEvent @ content-tools.min.js:4
(anonymous) @ content-tools.min.js:5
```

**Comment by nliautaud** [comment]
Hi, thanks for the report. The upload was fine, but the `<img/>` tag `src` wasn't including the Pico install base url. Could you test the fix 58ca8ee7d60cbc390a17b4d5241f4413dae06ddf above ?

**Comment by oleteacher** [comment]
I made the change on V2 Beta 3 and still no image inserted into content. Cleared cache and cookies but still getting:

```
File(13539)lastModified: 1499535957000lastModifiedDate: Sat Jul 08 2017 12:45:57 GMT-0500 (Central Daylight Time) {}name: "avatar04.png"size: 13539type: "image/png"webkitRelativePath: ""__proto__: File

Uncaught TypeError: Cannot read property 'path' of undefined
    at XMLHttpRequest.xhrComplete (editor.js:73)
```
Tried same fix on V1 and same error produced.

**Comment by nliautaud** [comment]
Hi, thanks for the follow-up. Some data where missing in the server response indeed.

I've clarified the editor logs, so you should get something like : 

![image](https://user-images.githubusercontent.com/761761/39928847-b4f071c8-5536-11e8-9e40-7d7eb3832b8c.png)

Could you test the added fixes ? (see #11)

**Comment by oleteacher** [comment]
Yes! That works great.

Like to get rid of the debug message that appears in green box (appears right top after saving) though.

The plugin is great, thank you.

Be nice to be able to:

Align image left|right|center and maybe allow little styling. Example of current use:
![image](https://user-images.githubusercontent.com/26278259/39935552-09527982-550f-11e8-9e43-82975f97ee5b.png)

Thanks again and since fixed issue, closing this:)

**Comment by nliautaud** [comment]
Great ! Feel free to add issues for the other features you think of !
