### ISSUE TITLE
Don't working with pico-users plugin

### ISSUE THREAD

**Issue by Tauxxx** [nliautaud/pico-content-editor#9]
I added to config

```
$config['users'] = array(
    'admin' => '???',
    'editors' => array(
        'bill' => '???'
    )
);
$config['rights'] = array(
    'PicoContentEditor' => 'admin',
    'PicoContentEditor/save' => 'editors',
);
```

added to index.twig

```
{{ content_editor }}
{{ login_form }}
</body>
```

Authentitication working, but content_editor with pico users don't working. 
I use latest version plugins .

Without pico-users plugin pico-content-editor working correctly.

**Comment by nliautaud** [comment]
Hi, thanks for the report.
Are you using Pico 1 or pico 2, and have you installed other plugins ?
Do you have any errors and warnings ? ([Pico debug](https://github.com/blocknotes/pico_debug) may be useful)

**Comment by Tauxxx** [comment]
Pico 1.0.6 
Plugins loaded :
```
onPluginsLoaded | plugins = PicoDeprecated, PicoParsePagesContent, PicoExcerpt, DummyPlugin, PicoContentEditor, PicoUsers, zz_pico_debug

```
Debug haven't errors or warning messages.

**Comment by CryDesign** [comment]
Hey Guys,
the Problem here ist that "PicoUsers" must be loaded before "PicoContentEditor".
So for example go into your "Plugins" folder an rename "PicoUsers" to maybe "0PicoUsers".
Then it will work.

**Comment by nliautaud** [comment]
PicoUsers should indeed be loaded first. Did you kept PicoUsers in its folder `45-PicoUsers` ? I should maybe emphase that the directory nomenclature is required in PicoUsers doc.

**Comment by CryDesign** [comment]
>  I should maybe emphase that the directory nomenclature is required in PicoUsers doc.

Would be not bad yeah
